tb/mocks/signals_rom_ip_mock.sv
tb/mocks/r2fft_tribuf_impl_mock.sv
rtl/common/hexa7seg.v
rtl/frontend/i2s_master_clock_gen.sv
rtl/frontend/i2s_rx_adapter_24.sv
rtl/frontend/i2s_fft_tx_adapter.sv
rtl/common/sample_width_adapter_24_to_18.sv
rtl/common/fft_control.sv
rtl/common/fft_dma_reader.sv
rtl/common/fft_tx_bridge_fifo.sv
rtl/ip/output_fifo/fft_output_fifo_bb.v
rtl/core/aces_audio_to_fft_pipeline.sv
rtl/core/aces.sv
rtl/stimulus/i2s_stimulus_manager_rom.sv
rtl/top/top_level_test.sv
tb/integration/tb_top_level_test.sv
