# Real-IP-oriented manifest for isolated FFT diagnosis in the board top-level.
rtl/ip/rom/signals_rom_ip.v
rtl/common/hexa7seg.v
rtl/frontend/i2s_master_clock_gen.sv
rtl/frontend/i2s_rx_adapter_24.sv
rtl/frontend/i2s_fft_tx_adapter.sv
rtl/common/sample_width_adapter_24_to_18.sv
rtl/common/fft_control.sv
rtl/common/fft_dma_reader.sv
rtl/common/fft_tx_bridge_fifo.sv
rtl/ip/output_fifo/fft_output_fifo.v
rtl/core/aces_audio_to_fft_pipeline.sv
rtl/core/aces.sv
rtl/stimulus/i2s_stimulus_manager_rom.sv
submodules/R2FFT_corrected/hdl/R2FFT.sv
submodules/R2FFT_corrected/hdl/R2FFT_tribuf.sv
submodules/R2FFT_corrected/hdl/bfp_Shifter.sv
submodules/R2FFT_corrected/hdl/bfp_bitWidthAcc.sv
submodules/R2FFT_corrected/hdl/bfp_bitWidthDetector.sv
submodules/R2FFT_corrected/hdl/bfp_maxBitWidth.sv
submodules/R2FFT_corrected/hdl/bitReverseCounter.sv
submodules/R2FFT_corrected/hdl/butterflyCore.sv
submodules/R2FFT_corrected/hdl/butterflyUnit.sv
submodules/R2FFT_corrected/hdl/fftAddressGenerator.sv
submodules/R2FFT_corrected/hdl/radix2Butterfly.sv
submodules/R2FFT_corrected/hdl/ramPipelineBridge.sv
submodules/R2FFT_corrected/hdl/readBusMux.sv
submodules/R2FFT_corrected/hdl/readBusMux_tribuf.sv
submodules/R2FFT_corrected/hdl/twiddleFactorRomBridge.sv
submodules/R2FFT_corrected/hdl/writeBusMux.sv
submodules/R2FFT_corrected/hdl/writeBusMux_tribuf.sv
submodules/R2FFT_corrected/quartus/r2fft_impl.sv
submodules/R2FFT_corrected/quartus/r2fft_tribuf_impl.sv
submodules/R2FFT_corrected/quartus/twrom.v
submodules/R2FFT_corrected/quartus/dpram.v
rtl/top/top_level_test.sv
tb/integration/tb_top_level_fft_isolated.sv
